name = "falko-frontend"
compatibility_date = "2025-09-13"
pages_build_output_dir = ".vercel/output/static"
compatibility_flags = ["nodejs_compat_populate_process_env"]

[vars]
## Cloudflare Pages runtime env vars (NEXT_PUBLIC_* are inlined do bundla)
## UWAGA: Poniższe wartości są publiczne (publishable key). Sekrety admina NIE powinny tu trafiać.
NEXT_PUBLIC_MEDUSA_BACKEND_URL = "https://backend-server-production-030d.up.railway.app"
NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY = "pk_01J7QF8Z9X8J7QF8Z9X8J7QF8Z"



# NOTE: Pages ignoruje sekcję [build] w wrangler.toml – build command ustaw w UI (npm run build:cf)
