name = "falko-frontend"
compatibility_date = "2025-09-13"
pages_build_output_dir = ".vercel/output/static"
compatibility_flags = ["nodejs_compat_populate_process_env"]

# [vars] - NIE używaj dla NEXT_PUBLIC_* zmiennych!
# NEXT_PUBLIC_* muszą być dostępne podczas BUILDU, nie runtime.
# Ustaw je w Cloudflare Pages Dashboard > Settings > Environment variables
# lub jako build-time env vars w deployment settings.

# Przykład zmiennych które MOGĄ być w [vars] (runtime-only):
# [vars]
# INTERNAL_API_KEY = "secret-only-for-server-side"



# NOTE: Pages ignoruje sekcję [build] w wrangler.toml – build command ustaw w UI (npm run build:cf)
