name = "falko"
compatibility_date = "2025-09-13"
pages_build_output_dir = ".vercel/output/static"
compatibility_flags = ["nodejs_compat_populate_process_env"]

# Environment variables dla build-time (dostępne podczas next build)
[vars]
NEXT_PUBLIC_MEDUSA_BACKEND_URL = "https://backend-server-production-030d.up.railway.app"  
NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY = "pk_01J7QF8Z9X8J7QF8Z9X8J7QF8Z"

# Environment-specific overrides (opcjonalnie)
[env.preview]
vars = { NEXT_PUBLIC_MEDUSA_BACKEND_URL = "https://backend-server-production-030d.up.railway.app" }

[env.production] 
vars = { NEXT_PUBLIC_MEDUSA_BACKEND_URL = "https://backend-server-production-030d.up.railway.app", NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY = "pk_01J7QF8Z9X8J7QF8Z9X8J7QF8Z" }



# NOTE: Pages ignoruje sekcję [build] w wrangler.toml – build command ustaw w UI (npm run build:cf)
